const posts =[
  {
    id: 1,
    name: "John Doe",
    profileimage: "https://example.com/john.jpg",
    description: "A software engineer with a passion for coding and technology.",
    likes: 150,
    comments: 100,
    shares: 3,
    postimage: "https://example.com/post1.jpg",
    postdate: "2023-10-01",
    posttime: "10:00 AM",
    posttext: "Just completed a new project! Check it out.",
    postlink: "https://example.com/project1",
  },
  {
    id: 2,
    name: "Jane Smith",
    profileimage: "https://example.com/jane.jpg",
    description: "A digital artist who loves to create and share art.",
    likes: 200,
    comments: 150,
    shares: 5,
    postimage: "https://example.com/post2.jpg",
    postdate: "2023-10-02",
    posttime: "11:00 AM",
    posttext: "Here's my latest artwork! Hope you like it.",
    postlink: "https://example.com/artwork1",
  },
  {
    id: 3,
    name: "Alice Johnson",
    profileimage: "https://example.com/alice.jpg",
    description: "A travel blogger exploring the world one city at a time.",
    likes: 300,
    comments: 250,
    shares: 10,
    postimage: "https://example.com/post3.jpg",
    postdate: "2023-10-03",
    posttime: "12:00 PM",
    posttext: "Just visited this beautiful place! Check out my blog for more.",
    postlink: "https://example.com/travelblog1",
  },
  {
    id: 4,
    name: "Bob Brown",
    profileimage: "https://example.com/bob.jpg",
    description: "A fitness enthusiast sharing workout tips and healthy living.",
    likes: 180,
    comments: 120,
    shares: 4,
    postimage: "https://example.com/post4.jpg",
    postdate: "2023-10-04",
    posttime: "1:00 PM",
    posttext: "Just finished a great workout! Stay fit everyone!",
    postlink: "https://example.com/fitness1",
  },{
    id: 5,
    name: "Charlie Green",
    profileimage: "https://example.com/charlie.jpg",
    description: "A food lover sharing recipes and restaurant reviews.",
    likes: 220,
    comments: 180,
    shares: 6,
    postimage: "https://example.com/post5.jpg",
    postdate: "2023-10-05",
    posttime: "2:00 PM",
    posttext: "Tried a new recipe today! Check it out on my blog.",
    postlink: "https://example.com/foodblog1",
  },{
    id: 6,
    name: "Diana Prince",
    profileimage: "https://example.com/diana.jpg",
    description: "A superhero in disguise, fighting for justice and equality.",
    likes: 500,
    comments: 400,
    shares: 20,
    postimage: "https://example.com/post6.jpg",
    postdate: "2023-10-06",
    posttime: "3:00 PM",
    posttext: "Remember, with great power comes great responsibility.",
    postlink: "https://example.com/superhero1",
  },{
    id: 7,
    name: "Ethan Hunt",
    profileimage: "https://example.com/ethan.jpg",
    description: "An action hero on a mission to save the world.",
    likes: 350,
    comments: 300,
    shares: 15,
    postimage: "https://example.com/post7.jpg",
    postdate: "2023-10-07",
    posttime: "4:00 PM",
    posttext: "Mission accomplished! Stay tuned for the next adventure.",
    postlink: "https://example.com/actionhero1",
  },{
    id: 8,
    name: "Fiona Apple",
    profileimage: "https://example.com/fiona.jpg",
    description: "A musician sharing my latest songs and performances.",
    likes: 400,
    comments: 350,
    shares: 12,
    postimage: "https://example.com/post8.jpg",
    postdate: "2023-10-08",
    posttime: "5:00 PM",
    posttext: "Just released a new single! Listen now on my website.",
    postlink: "https://example.com/music1",
  },{
    id: 9,
    name: "George Lucas",
    profileimage: "https://example.com/george.jpg",
    description: "A filmmaker creating epic stories and adventures.",
    likes: 600,
    comments: 500,
    shares: 25,
    postimage: "https://example.com/post9.jpg",
    postdate: "2023-10-09",
    posttime: "6:00 PM",
    posttext: "Excited to share my latest film project with you all!",
    postlink: "https://example.com/film1",
  },{
    id: 10,
    name: "Hannah Montana",
    profileimage: "https://example.com/hannah.jpg",
    description: "A pop star living the double life of a normal teenager.",
    likes: 450,
    comments: 400,
    shares: 18,
    postimage: "https://example.com/post10.jpg",
    postdate: "2023-10-10",
    posttime: "7:00 PM",
    posttext: "Can't wait for my next concert! Tickets available now.",
    postlink: "https://example.com/concert1",
  },{
    id: 11,
    name: "Ian Fleming",
    profileimage: "https://example.com/ian.jpg",
    description: "An author known for creating iconic spy characters.",
    likes: 320,
    comments: 280,
    shares: 8,
    postimage: "https://example.com/post11.jpg",
    postdate: "2023-10-11",
    posttime: "8:00 PM",
    posttext: "Just finished writing my latest novel! Stay tuned for the release.",
    postlink: "https://example.com/book1",
  },{
    id: 12,
    name: "Julia Roberts",
    profileimage: "https://example.com/julia.jpg",
    description: "An actress sharing my journey in the film industry.",
    likes: 550,
    comments: 450,
    shares: 22,
    postimage: "https://example.com/post12.jpg",
    postdate: "2023-10-12",
    posttime: "9:00 PM",
    posttext: "Thrilled to be part of this amazing project! More details soon.",
    postlink: "https://example.com/movie1",
  },{
    id: 13,
    name: "Kevin Hart",
    profileimage: "https://example.com/kevin.jpg",
    description: "A comedian bringing laughter and joy to everyone.",
    likes: 700,
    comments: 600,
    shares: 30,
    postimage: "https://example.com/post13.jpg",
    postdate: "2023-10-13",
    posttime: "10:00 PM",
    posttext: "Just finished a hilarious show! Can't wait to share the laughs.",
    postlink: "https://example.com/comedy1",
  },{
    id: 14,
    name: "Laura Croft",
    profileimage: "https://example.com/laura.jpg",
    description: "An adventurer exploring ancient ruins and treasures.",
    likes: 400,
    comments: 350,
    shares: 15,
    postimage: "https://example.com/post14.jpg",
    postdate: "2023-10-14",
    posttime: "11:00 PM",
    posttext: "Just discovered a hidden temple! More adventures to come.",
    postlink: "https://example.com/adventure1",
  },{
    id: 15,
    name: "Mike Tyson",
    profileimage: "https://example.com/mike.jpg",
    description: "A boxing legend sharing my journey in the ring.",
    likes: 800,
    comments: 700,
    shares: 35,
    postimage: "https://example.com/post15.jpg",
    postdate: "2023-10-15",
    posttime: "12:00 AM",
    posttext: "Training hard for my next fight! Stay tuned for updates.",
    postlink: "https://example.com/boxing1",
  },{
    id: 16,
    name: "Nina Simone",
    profileimage: "https://example.com/nina.jpg",
    description: "A singer-songwriter sharing my music and activism.",
    likes: 500,
    comments: 450,
    shares: 20,
    postimage: "https://example.com/post16.jpg",
    postdate: "2023-10-16",
    posttime: "1:00 AM",
    posttext: "Music is a powerful tool for change. Let's make a difference together.",
    postlink: "https://example.com/music2",
  },{
    id: 17,
    name: "Oscar Wilde",
    profileimage: "https://example.com/oscar.jpg",
    description: "A playwright and poet known for my wit and humor.",
    likes: 600,
    comments: 550,
    shares: 28,
    postimage: "https://example.com/post17.jpg",
    postdate: "2023-10-17",
    posttime: "2:00 AM",
    posttext: "Be yourself; everyone else is already taken.",
    postlink: "https://example.com/writing1",
  },{
    id: 18,
    name: "Peter Parker",
    profileimage: "https://example.com/peter.jpg",
    description: "A photographer and superhero balancing life and responsibilities.",
    likes: 750,
    comments: 650,
    shares: 32,
    postimage: "https://example.com/post18.jpg",
    postdate: "2023-10-18",
    posttime: "3:00 AM",
    posttext: "With great power comes great responsibility. Always remember that.",
    postlink: "https://example.com/superhero2",
  },{
    id: 19,
    name: "Quentin Tarantino",
    profileimage: "https://example.com/quentin.jpg",
    description: "A filmmaker known for my unique storytelling style.",
    likes: 900,
    comments: 800,
    shares: 40,
    postimage: "https://example.com/post19.jpg",
    postdate: "2023-10-19",
    posttime: "4:00 AM",
    posttext: "Excited to share my latest film project with you all!",
    postlink: "https://example.com/film2",
  },{
    id: 20,
    name: "Rachel Green",
    profileimage: "https://example.com/rachel.jpg",
    description: "A fashion enthusiast sharing my style tips and trends.",
    likes: 850,
    comments: 750,
    shares: 38,
    postimage: "https://example.com/post20.jpg",
    postdate: "2023-10-20",
    posttime: "5:00 AM",
    posttext: "Fashion is about expressing yourself. Be bold, be you!",
    postlink:"https://example.com/fashion1"
  },{
    id: 21,
    name: "Sam Winchester",
    profileimage: "https://example.com/sam.jpg",
    description: "A hunter of supernatural creatures, protecting humanity.",
    likes: 400,
    comments: 350,
    shares: 15,
    postimage: "https://example.com/post21.jpg",
    postdate: "2023-10-21",
    posttime: "6:00 AM",
    posttext: "Always stay vigilant. The world is full of mysteries.",
    postlink: "https://example.com/hunting1"
  },{
    id: 22,
    name: "Tina Fey",
    profileimage: "https://example.com/tina.jpg",
    description: "A comedian and writer bringing laughter to the world.",
    likes: 700,
    comments: 600,
    shares: 30,
    postimage: "https://example.com/post22.jpg",
    postdate: "2023-10-22",
    posttime: "7:00 AM",
    posttext: "Laughter is the best medicine. Let's spread joy together!",
    postlink: "https://example.com/comedy2"
  },{
    id: 23,
    name: "Ursula K. Le Guin",
    profileimage: "https://example.com/ursula.jpg",
    description: "A science fiction and fantasy author exploring new worlds.",
    likes: 600,
    comments: 550,
    shares: 28,
    postimage: "https://example.com/post23.jpg",
    postdate: "2023-10-23",
    posttime: "8:00 AM",
    posttext: "Imagination is the only weapon in the war against reality.",
    postlink: "https://example.com/writing2"
  },{
    id: 24,
    name: "Vincent van Gogh",
    profileimage: "https://example.com/vincent.jpg",
    description: "A painter sharing my art and passion for creativity.",
    likes: 800,
    comments: 700,
    shares: 35,
    postimage: "https://example.com/post24.jpg",
    postdate: "2023-10-24",
    posttime: "9:00 AM",
    posttext: "Art is not what you see, but what you make others see.",
    postlink: "https://example.com/art2"
  },{
    id: 25,
    name: "Winston Churchill",
    profileimage: "https://example.com/winston.jpg",
    description: "A leader known for my speeches and resilience.",
    likes: 900,
    comments: 800,
    shares: 40,
    postimage: "https://example.com/post25.jpg",
    postdate: "2023-10-25",
    posttime: "10:00 AM",
    posttext:"Success is not final, failure is not fatal; it is the courage to continue that counts.",
    postlink:"https://example.com/speech1"
  },{
    id: 26,
    name: "Xena Warrior Princess",
    profileimage: "https://example.com/xena.jpg",
    description: "A warrior princess fighting for justice and peace.",
    likes: 500,
    comments: 450,
    shares: 20,
    postimage: "https://example.com/post26.jpg",
    postdate: "2023-10-26",
    posttime: "11:00 AM",
    posttext: "Strength and honor are my guiding principles.",
    postlink: "https://example.com/warrior1"
  },{
    id: 27,
    name: "Yoda",
    profileimage: "https://example.com/yoda.jpg",
    description: "A wise Jedi Master sharing knowledge and wisdom.",
    likes: 1000,
    comments: 900,
    shares: 50,
    postimage: "https://example.com/post27.jpg",
    postdate: "2023-10-27",
    posttime: "12:00 PM",
    posttext:"Do or do not, there is no try.",
    postlink:"https://example.com/jedi1"
  },{
    id: 28,
    name: "Zoe Saldana",
    profileimage: "https://example.com/zoe.jpg",
    description: "An actress known for my roles in sci-fi and action films.",
    likes: 750,
    comments: 650,
    shares: 32,
    postimage:"https://example.com/post28.jpg",
    postdate:"2023-10-28",
    posttime:"1:00 PM",
    posttext:"Excited to share my latest film project with you all!",
    postlink:"https://example.com/film3"
  },
  {
    id: 29,
    name: "Alan Turing",
    profileimage: "https://example.com/alan.jpg",
    description: "A mathematician and computer scientist known for my contributions to cryptography.",
    likes: 600,
    comments: 550,
    shares: 28,
    postimage: "https://example.com/post29.jpg",
    postdate: "2023-10-29",
    posttime: "2:00 PM",
    posttext: "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    postlink: "https://example.com/computer1"
  },
  {
    id: 30,
    name: "Beyoncé Knowles",
    profileimage: "https://example.com/beyonce.jpg",
    description: "A singer and performer sharing my music and journey.",
    likes: 1200,
    comments: 1100,
    shares: 60,
    postimage: "https://example.com/post30.jpg",
    postdate: "2023-10-30",
    posttime: "3:00 PM",
    posttext:"Who run the",
    postlink: "https://example.com/music3"
  }
]


const videos=[
  {
    id:1,
    name:'john',
    profileimage:'https://picsum.photos/seed/sunset/600/400',
    description:'A beautiful sunset over the mountains.',
    likes: 1200,
    comments: 300,
    shares: 50,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-01',
    posttime: '10:00 AM',
    posttext: 'Check out this amazing sunset I captured during my hike!',
    postlink: 'https://example.com/sunset-video',
  },
  {
    id:2,
    name:'jane',
    profileimage:'https://picsum.photos/seed/sunrise/600/400',
    description:'A stunning sunrise over the ocean.',
    likes: 1500,
    comments: 400,
    shares: 70,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-02',
    posttime: '11:00 AM',
    posttext: 'Witness the beauty of a sunrise at the beach!',
    postlink: 'https://example.com/sunrise-video',
  },
  {
    id:3,
    name:'alice',
    profileimage:'https://picsum.photos/seed/mountains/600/400',
    description:'A breathtaking view of the mountains.',
    likes: 1800,
    comments: 500,
    shares: 90,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-03',
    posttime: '12:00 PM',
    posttext: 'Exploring the majestic mountains and capturing their beauty!',
    postlink: 'https://example.com/mountains-video',
  },
  {
    id:4,
    name:'bob',
    profileimage:'https://picsum.photos/seed/lake/600/400',
    description:'A serene lake surrounded by trees.',
    likes: 1600,
    comments: 450,
    shares: 80,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-04',
    posttime: '1:00 PM',
    posttext: 'Relaxing by the lake and enjoying nature\'s tranquility.',
    postlink: 'https://example.com/lake-video',
  },
  {
    id:5,
    name:'charlie',
    profileimage:'https://picsum.photos/seed/forest/600/400',
    description:'A walk through a lush green forest.',
    likes: 1400,
    comments: 350,
    shares: 60,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-05',
    posttime: '2:00 PM',
    posttext: 'Immerse yourself in the beauty of the forest!',
    postlink: 'https://example.com/forest-video',
  },
  {
    id:6,
    name:'diana',
    profileimage:'https://picsum.photos/seed/beach/600/400',
    description:'A relaxing day at the beach.',
    likes: 2000,
    comments: 600,
    shares: 100,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-06',
    posttime: '3:00 PM',
    posttext: 'Enjoying the sun, sand, and sea at the beach!',
    postlink: 'https://example.com/beach-video',
  },
  {
    id:7,
    name:'ethan',
    profileimage:'https://picsum.photos/seed/city/600/400',
    description:'A vibrant cityscape at night.',
    likes: 1700,
    comments: 500,
    shares: 85,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-07',
    posttime: '4:00 PM',
    posttext: 'Exploring the city lights and nightlife!',
    postlink: 'https://example.com/city-video',
  },
  {
    id:8,
    name:'fiona',
    profileimage:'https://picsum.photos/seed/wildlife/600/400',
    description:'A close encounter with wildlife in their natural habitat.',
    likes: 1900,
    comments: 550,
    shares: 95,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-08',
    posttime: '5:00 PM',
    posttext: 'Witnessing the beauty of wildlife up close!',
    postlink: 'https://example.com/wildlife-video',
  },
  {
    id:9,
    name:'george',
    profileimage:'https://picsum.photos/seed/snow/600/400',
    description:'A snowy landscape during winter.',
    likes: 1300,
    comments: 300,
    shares: 55,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-09',
    posttime: '6:00 PM',
    posttext: 'Enjoying the winter wonderland and snow activities!',
    postlink: 'https://example.com/snow-video',
  },
  {
    id:10,
    name:'hannah',
    profileimage:'https://picsum.photos/seed/desert/600/400',
    description:'A mesmerizing desert landscape at sunset.',
    likes: 2100,
    comments: 700,
    shares: 120,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-10',
    posttime: '7:00 PM',  
    posttext: 'Exploring the beauty of the desert and its unique landscapes!',
    postlink: 'https://example.com/desert-video',
  },
  {
    id:11,
    name:'ian',
    profileimage:'https://picsum.photos/seed/river/600/400',
    description:'A peaceful river flowing through the countryside.',
    likes: 1100,
    comments: 250,
    shares: 40,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-11',
    posttime: '8:00 PM',
    posttext: 'Relaxing by the river and enjoying the serene environment.',
    postlink: 'https://example.com/river-video',
  },
  {
    id:12,
    name:'julia',
    profileimage:'https://picsum.photos/seed/garden/600/400',
    description:'A beautiful garden filled with blooming flowers.',
    likes: 1600,
    comments: 400,
    shares: 75,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-12',
    posttime: '9:00 PM',
    posttext: 'Exploring the vibrant colors and scents of the garden!',
    postlink: 'https://example.com/garden-video',
  },
  {
    id:13,
    name:'kevin',
    profileimage:'https://picsum.photos/seed/canyon/600/400',
    description:'A stunning view of a canyon during sunset.',
    likes: 1800,
    comments: 500,
    shares: 90,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-13',
    posttime: '10:00 PM',
    posttext: 'Capturing the beauty of nature in the canyon!',
    postlink: 'https://example.com/canyon-video',
  },
  {
      id:14,
      name:'laura',
      profileimage:'https://picsum.photos/seed/island/600/400',
      description:'A tropical island paradise with crystal clear waters.',
      likes: 2000,
      comments: 600,
      shares: 100,
      videolink:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      postdate: '2023-10-14',
      posttime: '11:00 PM',
      posttext: 'Exploring the beauty of a tropical island paradise!',
      postlink: 'https://example.com/island-video',
  },
  {
    id:15,
    name:'mike',
    profileimage:'https://picsum.photos/seed/volcano/600/400',
    description:'A majestic volcano with a stunning view.',
    likes: 2200,
    comments: 700,
    shares: 120,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-15',
    posttime: '12:00 AM',
    posttext: 'Witnessing the power and beauty of a volcano!',
    postlink: 'https://example.com/volcano-video',
  },
  {
    id:16,
    name:'nina',
    profileimage:'https://picsum.photos/seed/bridge/600/400',
    description:'A beautiful bridge connecting two sides of a river.',
    likes: 1400,
    comments: 350,
    shares: 60,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-16',
    posttime: '1:00 AM',
    posttext: 'Exploring the architectural beauty of this bridge!',
    postlink: 'https://example.com/bridge-video',
  },
  {
    id:17,
    name:'oscar',
    profileimage:'https://picsum.photos/seed/cityscape/600/400',
    description:'A stunning cityscape with skyscrapers and lights.',
    likes: 1700,
    comments: 500,
    shares: 85,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-17',
    posttime: '2:00 AM',
    posttext: 'Capturing the vibrant energy of the city at night!',
    postlink: 'https://example.com/cityscape-video',
  },
  {
      id:18,
      name:'peter',
      profileimage:'https://picsum.photos/seed/waterfall/600/400',
      description:'A breathtaking waterfall cascading down rocks.',
      likes: 1900,
      comments: 550,
      shares: 95,
      videolink:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      postdate:'2023-10-18',
      posttime:'3:00 AM',
      posttext:'Witnessing the power and beauty of a waterfall!',
      postlink:'https://example.com/waterfall-video'
  },
  {
      id:19,
      name:'quentin',
      profileimage:'https://picsum.photos/seed/desert2/600/400',
      description:'A mesmerizing desert landscape with dunes.',
      likes: 2100,
      comments: 700,
      shares: 120,
      videolink:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      postdate: '2023-10-19',
      posttime: '4:00 AM',
      posttext: 'Exploring the beauty of the desert and its unique landscapes!',
      postlink: 'https://example.com/desert2-video',
  },
  {
    id:20,
    name:'rachel',
    profileimage:'https://picsum.photos/seed/skyline/600/400',
    description:'A stunning skyline view of a city at dusk.',
    likes: 1600,
    comments: 400,
    shares: 75,
    videolink: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    postdate: '2023-10-20',
    posttime: '5:00 AM',
    posttext: 'Capturing the beauty of the city skyline at dusk!',
    postlink: 'https://example.com/skyline-video',
  }, {
    id: 21,
    name: "Sam Winchester",
    profileimage: "https://picsum.photos/seed/sam/600/400",
    description: "A hunter of supernatural creatures, protecting humanity.",
    likes: 400,
    comments: 350,
    shares: 15,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-21",
    posttime: "6:00 AM",
    posttext: "Always stay vigilant. The world is full of mysteries.",
    postlink: "https://example.com/hunting1"
  }, {
    id: 22,
    name: "Tina Fey",
    profileimage: "https://picsum.photos/seed/tina/600/400",
    description: "A comedian and writer bringing laughter to the world.",
    likes: 700,
    comments: 600,
    shares: 30,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-22",
    posttime: "7:00 AM",
    posttext: "Laughter is the best medicine. Let's spread joy together!",
    postlink: "https://example.com/comedy2"
  }, {
    id: 23,
    name: "Ursula K. Le Guin",
    profileimage: "https://picsum.photos/seed/ursula/600/400",
    description: "A science fiction and fantasy author exploring new worlds.",
    likes: 600,
    comments: 550,
    shares: 28,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-23",
    posttime: "8:00 AM",
    posttext: "Imagination is the only weapon in the war against reality.",
    postlink: "https://example.com/writing2"
  }, {
    id: 24,
    name: "Vincent van Gogh",
    profileimage: "https://picsum.photos/seed/vincent/600/400",
    description: "A painter sharing my art and passion for creativity.",
    likes: 800,
    comments: 700,
    shares: 35,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-24",
    posttime: "9:00 AM",
    posttext: "Art is not what you see, but what you make others see.",
    postlink: "https://example.com/art2"
  },
  {
    id: 25,
    name: "Winston Churchill",
    profileimage: "https://picsum.photos/seed/winston/600/400",
    description: "A leader known for my speeches and resilience.",
    likes: 900,
    comments: 800,
    shares: 40,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-25",
    posttime: "10:00 AM",
    posttext:"Success is not final, failure is not fatal; it is the courage to continue that counts.",
    postlink:"https://example.com/speech1"
  }, {
    id: 26,
    name: "Xena Warrior Princess",
    profileimage: "https://picsum.photos/seed/xena/600/400",
    description: "A warrior princess fighting for justice and peace.",
    likes: 500,
    comments: 450,
    shares: 20,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-26",
    posttime: "11:00 AM",
    posttext: "Strength and honor are my guiding principles.",
    postlink: "https://example.com/warrior1"
  }, {
    id: 27,
    name: "Yoda",
    profileimage: "https://picsum.photos/seed/yoda/600/400",
    description: "A wise Jedi Master sharing knowledge and wisdom.",
    likes: 1000,
    comments: 900,
    shares: 50,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-27",
    posttime: "12:00 PM",
    posttext:"Do or do not, there is no try.",
    postlink:"https://example.com/jedi1"
  }, {
      id: 28,
      name: "Zoe Saldana",
      profileimage: "https://picsum.photos/seed/zoe/600/400",
      description: "An actress known for my roles in sci-fi and action films.",
      likes: 750,
      comments: 650,
      shares: 32,
      videolink:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      postdate:'2023-10-28',
      posttime:'1:00 PM',
      posttext:'Excited to share my latest film project with you all!',
      postlink:'https://example.com/film3'
  }, {
    id: 29,
    name: "Alan Turing",
    profileimage: "https://picsum.photos/seed/alan/600/400",
    description: "A mathematician and computer scientist known for my contributions to cryptography.",
    likes: 600,
    comments: 550,
    shares: 28,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-29",
    posttime: "2:00 PM",
    posttext: "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    postlink: "https://example.com/computer1"
  }, {
    id: 30,
    name: "Beyoncé Knowles",
    profileimage: "https://picsum.photos/seed/beyonce/600/400",
    description: "A singer and performer sharing my music and journey.",
    likes: 1200,
    comments: 1100,
    shares: 60,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-30",
    posttime: "3:00 PM",
    posttext:"Who run the world?",
    postlink:"https://example.com/music3"
  }, {
    id: 31,
    name: "Alice Johnson",
    profileimage: "https://picsum.photos/seed/alice/600/400",
    description: "A digital artist sharing my latest creations.",
    likes: 800,
    comments: 700,
    shares: 35,
    videolink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    postdate: "2023-10-31",
    posttime: "4:00 PM",
    posttext: "Check out my new digital art piece!",
    postlink: "https://example.com/digitalart1"
  }
]

const notifications = [
  {
 id: 1,
 name: "John Doe",
 profileimage: "https://picsum.photos/seed/john/600/400",
 notification: 'like your video',
  },
  {
    id: 2,
    name: "Jane Smith", 
    profileimage: "https://picsum.photos/seed/jane/600/400",
    notification: 'commented on your post',
  },
  {
    id : 3,
    name: "Alice Johnson",
    profileimage: "https://picsum.photos/seed/alice/600/400",
    notification: 'shared your video',    
  },
  {
    id: 4,
    name: "Bob Brown",
    profileimage: "https://picsum.photos/seed/bob/600/400",
    notification: 'liked your post',
  },
  {
    id: 5,
    name: "Charlie Green",
    profileimage: "https://picsum.photos/seed/charlie/600/400",
    notification: 'started following you',
  },
  {
    id: 6,
    name: "Diana Prince",
    profileimage: "https://picsum.photos/seed/diana/600/400",
    notification: 'sent you a friend request',
  },
  {
    id: 7,
    name: "Ethan Hunt",
    profileimage: "https://picsum.photos/seed/ethan/600/400",
    notification: 'liked your video',
  },
  {
    id: 8,
    name: "Fiona Apple",
    profileimage: "https://picsum.photos/seed/fiona/600/400",
    notification: 'commented on your post',
  },
  {
    id: 9,
    name: "George Lucas",
    profileimage: "https://picsum.photos/seed/george/600/400",
    notification: 'shared your video',
  },
  {
    id: 10,
    name: "Hannah Montana",
    profileimage: "https://picsum.photos/seed/hannah/600/400",
    notification: 'liked your post',
  },
  {
    id: 11,
    name: "Ian Fleming",
    profileimage: "https://picsum.photos/seed/ian/600/400",
    notification: 'started following you',
  },
  {
    id: 12,
    name: "Julia Roberts",
    profileimage: "https://picsum.photos/seed/julia/600/400",
    notification: 'sent you a friend request',
  },
  {
    id: 13,
    name: "Kevin Hart",
    profileimage: "https://picsum.photos/seed/kevin/600/400",
    notification: 'liked your video',
  },
  {
    id: 14,
    name: "Laura Croft",
    profileimage: "https://picsum.photos/seed/laura/600/400",
    notification: 'commented on your post',
  },
  {
    id: 15,
    name: "Mike Tyson",
    profileimage: "https://picsum.photos/seed/mike/600/400",
    notification: 'shared your video',
  },
  {
    id: 16,
    name: "Nina Simone",
    profileimage: "https://picsum.photos/seed/nina/600/400",
    notification: 'liked your post',
  },
  {
    id: 17,
    name: "Oscar Wilde",
    profileimage: "https://picsum.photos/seed/oscar/600/400",
    notification: 'started following you',
  },
  {
    id: 18,
    name: "Peter Parker",
    profileimage: "https://picsum.photos/seed/peter/600/400",
    notification:'sent you a friend request',
  },
  {
      id :19,
      name:'Quentin Tarantino',
      profileimage:'https://picsum.photos/seed/tarantino/600/400',
      notification:'liked your video'
  },{
      id :20,
      name:'Rachel Green',
      profileimage:'https://picsum.photos/seed/rachelgreen/600/400',
      notification:'commented on your post'
  },{
      id :21,
      name:'Sam Winchester',
      profileimage:'https://picsum.photos/seed/samwinchester/600/400',
      notification:'shared your video'
  },{
      id :22,
      name:'Tina Fey',
      profileimage:'https://picsum.photos/seed/tinafey/600/400',
      notification:'liked your post'
  },{
      id :23,
      name:'Ursula K. Le Guin',
      profileimage: 'https://picsum.photos/seed/ursulakeguin/600/400',
      notification: 'started following you',
  },
  { 
    id :24,
    name:'Vincent van Gogh',
    profileimage: 'https://picsum.photos/seed/vincentvangogh/600/400',
    notification: 'sent you a friend request',
  },
  {
    id: 25,
    name: "Winston Churchill",
    profileimage: "https://picsum.photos/seed/winstonchurchill/600/400",
    notification: "liked your video",
  },{
    id: 26,
    name: "Xena Warrior Princess",
    profileimage: "https://picsum.photos/seed/xenawarriorprincess/600/400",
    notification: "commented on your post",
  },{
    id: 27,
    name: "Yoda",
    profileimage: "https://picsum.photos/seed/yoda/600/400",
    notification: "shared your video",
  },{
    id: 28,
    name: "Zoe Saldana",
    profileimage: "https://picsum.photos/seed/zoesaldana/600/400",
    notification: "liked your post",
  },{
      id :29,
      name:'Alan Turing',
      profileimage:'https://picsum.photos/seed/alanturing/600/400',
      notification:'started following you'
  },{
      id :30,
      name:'Beyoncé Knowles',
      profileimage:'https://picsum.photos/seed/beyonceknowles/600/400',
      notification:'sent you a friend request'
  },

]

const Friends = [

  {
    id: 1,
    name:'Alan Turing',
    profileimage: 'https://picsum.photos/seed/alanturing/600/400',
    muatualFriends: 5,
  },{
    id: 2,
    name:'Beyoncé Knowles',
    profileimage: 'https://picsum.photos/seed/beyonceknowles/600/400',
    muatualFriends: 10,
  },{
    id: 3,
    name:'Charlie Green',
    profileimage: 'https://picsum.photos/seed/charliegreen/600/400',
    muatualFriends: 3,
  },{
    id: 4,
    name:'Diana Prince',
    profileimage: 'https://picsum.photos/seed/dianaprince/600/400',
    muatualFriends: 8,
  },{
    id: 5,
    name:'Ethan Hunt',
    profileimage: 'https://picsum.photos/seed/ethanhunt/600/400',
    muatualFriends: 6,
  },{
    id: 6,
    name:'Fiona Apple',
    profileimage: 'https://picsum.photos/seed/fionaapple/600/400',
    muatualFriends: 4,
  },{
      id :7,
      name:'George Lucas',
      profileimage:'https://picsum.photos/seed/georgelucas/600/400',
      muatualFriends:7
  },{
      id :8,
      name:'Hannah Montana',
      profileimage:'https://picsum.photos/seed/hannahmontana/600/400',
      muatualFriends:9
  },{
    id: 9,
    name: "Ian Fleming",
    profileimage: "https://picsum.photos/seed/ianfleming/600/400",
    muatualFriends: 2,
  },{
    id: 10,
    name: "Julia Roberts",
    profileimage: "https://picsum.photos/seed/juliaroberts/600/400",
    muatualFriends: 12,
  },{
    id: 11,
    name: "Kevin Hart",
    profileimage: "https://picsum.photos/seed/kevinhart/600/400",
    muatualFriends: 15,
  },{
    id: 12,
    name: "Laura Croft",
    profileimage: "https://picsum.photos/seed/lauracroft/600/400",
    muatualFriends: 7,
  },{
      id :13,
      name:'Mike Tyson',
      profileimage:'https://picsum.photos/seed/miketyson/600/400',
      muatualFriends:11
  },{
      id :14,
      name:'Nina Simone',
      profileimage:'https://picsum.photos/seed/ninasimone/600/400',
      muatualFriends:4
  },{
    id: 15,
    name: "Oscar Wilde",
    profileimage: "https://picsum.photos/seed/oscarwilde/600/400",
    muatualFriends: 9,
  },{
    id: 16,
    name: "Peter Parker",
    profileimage: "https://picsum.photos/seed/peterparker/600/400",
    muatualFriends: 6,
  },{
      id :17,
      name:'Quentin Tarantino',
      profileimage:'https://picsum.photos/seed/quentintarantino/600/400',
      muatualFriends:8
  },{
      id :18,
      name:'Rachel Green',
      profileimage:'https://picsum.photos/seed/rachelgreen/600/400',
      muatualFriends:10
  },{
    id: 19,
    name: "Sam Winchester",
    profileimage: "https://picsum.photos/seed/samwinchester/600/400",
    muatualFriends: 5,
  },{
    id: 20,
    name: "Tina Fey",
    profileimage: "https://picsum.photos/seed/tinafey/600/400",
    muatualFriends: 3,
  },
  {
    id: 21,
    name: "Ursula K. Le Guin",
    profileimage: "https://picsum.photos/seed/ursulakeguin/600/400",
    muatualFriends: 6,
  },{
    id: 22,
    name: "Vincent van Gogh",
    profileimage: "https://picsum.photos/seed/vincentvangogh/600/400",
    muatualFriends: 8,
  },{
    id: 23,
    name: "Winston Churchill",
    profileimage: "https://picsum.photos/seed/winstonchurchill/600/400",
    muatualFriends: 4,
  },{
    id: 24,
    name: "Xena Warrior Princess",
    profileimage: "https://picsum.photos/seed/xenawarriorprincess/600/400",
    muatualFriends: 2,
  },{
      id :25,
      name:'Yoda',
      profileimage:'https://picsum.photos/seed/yoda/600/400',
      muatualFriends:5
  },{
      id :26,
      name:'Zoe Saldana',
      profileimage:'https://picsum.photos/seed/zoesaldana/600/400',
      muatualFriends:3
  },{
    id: 27,
    name: "Alan Turing",
    profileimage: "https://picsum.photos/seed/alanturing/600/400",
    muatualFriends: 6,
  },{
    id: 28,
    name: "Beyoncé Knowles",
    profileimage: "https://picsum.photos/seed/beyonceknowles/600/400",
    muatualFriends: 10,
  },{
    id: 29,
    name: "Alice Johnson",
    profileimage: "https://picsum.photos/seed/alicejohnson/600/400",
    muatualFriends: 4,
  },{
    id: 30,
    name: "Charlie Green",
    profileimage: "https://picsum.photos/seed/charliegreen/600/400",
    muatualFriends: 7,
  }
]
const marketplace =[
  {
    id: 1,
    name: 'Alice johnson',
    discription: 'A beautiful sunset over the mountains.',
    profileimage:'https://picsum.photos/seed/alice/600/400',
    itemimage:' https://picsum.photos/seed/sunset/600/400',
    price: 100,
    off: '10%',
  },{
    id: 2,
    name: 'Charlie green',
    discription: 'A stunning sunrise over the ocean.',
    profileimage: 'https://picsum.photos/seed/charlie/600/400',
    itemimage: 'https://picsum.photos/seed/sunrise/600/400',
    price: 150,
    off: '15%',
  }, {
    id: 3,
    name: 'Bob Brown',
    discription: 'A breathtaking view of the mountains.',
    profileimage: 'https://picsum.photos/seed/bob/600/400',
    itemimage: 'https://picsum.photos/seed/mountains/600/400',
    price: 200,
    off: '20%',
  },{
    id: 4,
    name: 'Diana Prince',
    discription: 'A serene lake surrounded by trees.',
    profileimage: 'https://picsum.photos/seed/diana/600/400',
    itemimage: 'https://picsum.photos/seed/lake/600/400',
    price: 120,
    off: '5%',
  },{
    id: 5,
    name: 'Ethan Hunt',
    discription: 'A walk through a lush green forest.',
    profileimage:'https://picsum.photos/seed/ethan/600/400',
    itemimage:'https://picsum.photos/seed/forest/600/400',
    price: 80,
    off: '8%',
  },{
      id :6,
      name:'Fiona Apple',
      discription:'A relaxing day at the beach.',
      profileimage:'https://picsum.photos/seed/fionaapple/600/400',
      itemimage:'https://picsum.photos/seed/beach/600/400',
      price: 90,
      off:'12%'
  },{
      id :7,
      name:'George Lucas',
      discription:'A vibrant cityscape at night.',
      profileimage:'https://picsum.photos/seed/georgelucas/600/400',
      itemimage:'https://picsum.photos/seed/cityscape/600/400',
      price: 110,
      off:'10%'
  },{
      id :8,
      name:'Hannah Montana',
      discription:'A close encounter with wildlife in their natural habitat.',
      profileimage:'https://picsum.photos/seed/hannahmontana/600/400',
      itemimage:'https://picsum.photos/seed/wildlife/600/400',
      price: 130,
      off:'15%'
  },{
    id :9,
    name:'Ian Fleming',
    discription:'A snowy landscape during winter.',
    profileimage:'https://picsum.photos/seed/flemingian/600/400',
    itemimage:'https://picsum.photos/seed/snow/600/400',
    price: 140,
    off: '18%',
  },{
    id :10,
    name:'Julia Roberts',
    discription:'A mesmerizing desert landscape at sunset.',
    profileimage:'https://picsum.photos/seed/juliaroberts/600/400',
    itemimage:'https://picsum.photos/seed/desert/600/400',
    price: 160,
    off: '20%',
  }, {
    id: 11,
    name: 'Kevin Hart',
    discription: 'A peaceful river flowing through the countryside.',
    profileimage: 'https://picsum.photos/seed/kevinhart/600/400',   
    itemimage: 'https://picsum.photos/seed/river/600/400',
    price: 70,
    off: '5%',
  },{
    id: 12,
    name: 'Laura Croft',
    discription: 'A beautiful garden filled with blooming flowers.',
    profileimage: 'https://picsum.photos/seed/lauracroft/600/400',
    itemimage: 'https://picsum.photos/seed/garden/600/400',
    price: 60,
    off: '7%',
  },{
      id :13,
      name:'Mike Tyson',
      discription:'A stunning view of a canyon during sunset.',
      profileimage:'https://picsum.photos/seed/miketyson/600/400',
      itemimage:'https://picsum.photos/seed/canyon/600/400',
      price: 130,
      off:'10%'
  },{
      id :14,
      name:'Nina Simone',
      discription:'A tropical island paradise with crystal clear waters.',
      profileimage:'https://picsum.photos/seed/ninasimone/600/400',
      itemimage:'https://picsum.photos/seed/island/600/400',
      price: 200,
      off:'15%'
  },{
    id: 15,
    name: "Oscar Wilde",
    discription: "A majestic volcano with a stunning view.",
    profileimage: "https://picsum.photos/seed/oscarwilde/600/400",
    itemimage: "https://picsum.photos/seed/volcano/600/400",
    price: 250,
    off: '20%',
  },{
    id: 16,
    name: "Peter Parker",
    discription: "A beautiful bridge connecting two sides of a river.",
    profileimage: "https://picsum.photos/seed/peterparker/600/400",
    itemimage: "https://picsum.photos/seed/bridge/600/400",
    price: 90,
    off: '10%',
  },{
      id :17,
      name:'Quentin Tarantino',
      discription:'A stunning cityscape with skyscrapers and lights.',
      profileimage:'https://picsum.photos/seed/tarantinoquentin/600/400',
      itemimage:'https://picsum.photos/seed/cityscape2/600/400',
      price: 180,
      off:'12%'
  },{
      id :18,
      name:'Rachel Green',
      discription:'A breathtaking waterfall cascading down rocks.',
      profileimage:'https://picsum.photos/seed/rachelgreen/600/400',
      itemimage:'https://picsum.photos/seed/waterfall/600/400',
      price: 220,
      off:'15%',
  },{
    id: 19,
    name: "Sam Winchester",
    discription: "A mesmerizing desert landscape with dunes.",
    profileimage: "https://picsum.photos/seed/samwinchester/600/400",
    itemimage: "https://picsum.photos/seed/desert2/600/400",
    price: 150,
    off: '10%',
  },{
    id: 20,
    name: "Tina Fey",
    discription: "A stunning skyline view of a city at dusk.",
    profileimage: "https://picsum.photos/seed/tinafey/600/400",
    itemimage: "https://picsum.photos/seed/skyline/600/400",
    price: 170,
    off: '8%',
  }
]

const messages =[
  {
    id: 1,
    name: 'Alice Johnson',
    profileimage: 'https://picsum.photos/seed/alice/600/400',
    message: 'Hey! How are you doing today?',
  },
  {
    id: 2,
    name: 'Bob Brown',
    profileimage: 'https://picsum.photos/seed/bob/600/400',
    message: 'Just finished a great book, want to discuss it?',
  },
  {
    id: 3,
    name: 'Charlie Green',
    profileimage: 'https://picsum.photos/seed/charlie/600/400',
    message: 'Let’s catch up over coffee this weekend!',
  },
  {
    id: 4,
    name: 'Diana Prince',
    profileimage: 'https://picsum.photos/seed/diana/600/400',
    message: 'I loved your recent post, it was inspiring!',
  },
  {
    id: 5,
    name: 'Ethan Hunt',
    profileimage: 'https://picsum.photos/seed/ethan/600/400',
    message: 'Are you free for a call later today?',
  },
  {
      id :6,
      name:'Fiona Apple',
      profileimage:'https://picsum.photos/seed/fionaapple/600/400',
      message:'Can you send me the details for the event next week?'
  },{
      id :7,
      name:'George Lucas',
      profileimage:'https://picsum.photos/seed/georgelucas/600/400',
      message:'I have some exciting news to share with you!'
  },{
      id :8,
      name:'Hannah Montana',
      profileimage:'https://picsum.photos/seed/hannahmontana/600/400',
      message:'Let’s plan a trip together soon!'
  },{
    id: 9,
    name: 'Ian Fleming',
    profileimage: 'https://picsum.photos/seed/ian/600/400',
    message: 'I found a great article you might like, check it out!',
  },{
    id: 10,
    name: 'Julia Roberts',
    profileimage: 'https://picsum.photos/seed/julia/600/400',
    message: 'Looking forward to our meeting next week!',
  },{
      id :11,
      name:'Kevin Hart',
      profileimage:'https://picsum.photos/seed/kevinhart/600/400',
      message:'Let’s collaborate on a project together!'
  },{
      id :12,
      name:'Laura Croft',
      profileimage:'https://picsum.photos/seed/lauracroft/600/400',
      message:'I need your advice on something important.'
  },{
    id: 13,
    name: 'Mike Tyson',
    profileimage: 'https://picsum.photos/seed/mike/600/400',
    message: 'Can you help me with a quick question?',
  },{
    id: 14,
    name: 'Nina Simone',
    profileimage: 'https://picsum.photos/seed/nina/600/400',
    message: 'I’m organizing an event, would love for you to join!',
  },{
      id :15,
      name:'Oscar Wilde',
      profileimage:'https://picsum.photos/seed/oscarwilde/600/400',
      message:'Your insights are always valuable, let’s chat soon.'
  },{
      id :16,
      name:'Peter Parker',
      profileimage:'https://picsum.photos/seed/peterparker/600/400',
      message:'I have some photos from the event, want to see them?'
  },{
    id: 17,
    name: "Quentin Tarantino",
    profileimage: "https://picsum.photos/seed/tarantino/600/400",
    message: "Let’s brainstorm some ideas for our next project!",
  },{
    id: 18,
    name: "Rachel Green",
    profileimage: "https://picsum.photos/seed/rachelgreen/600/400",
    message: "I loved your recent post, it was so relatable!",
  },{
      id :19,
      name:'Sam Winchester',
      profileimage: 'https://picsum.photos/seed/samwinchester/600/400',
      message: 'I have a new theory about the case we discussed.',
  },{
      id :20,
      name:'Tina Fey',
      profileimage: 'https://picsum.photos/seed/tinafey/600/400',
      message: 'I have a new comedy sketch idea, want to hear it?',
  },{
    id: 21,
    name: "Ursula K. Le Guin",
    profileimage: "https://picsum.photos/seed/ursulakeguin/600/400",
    message: "I’m working on a new story, would love your feedback!",
  },{
    id: 22,
    name: "Vincent van Gogh",
    profileimage: "https://picsum.photos/seed/vincentvangogh/600/400",
    message: "I’ve been inspired by your art, let’s collaborate!",
  },{
    id: 23,
    name: "Winston Churchill",
    profileimage: "https://picsum.photos/seed/winstonchurchill/600/400",
    message: "Your leadership skills are impressive, let’s connect!",
  },{
    id: 24,
    name: "Xena Warrior Princess",
    profileimage: "https://picsum.photos/seed/xenawarriorprincess/600/400",
    message: "I admire your strength and courage, let’s chat!",
  },{
      id :25,
      name:'Yoda',
      profileimage:'https://picsum.photos/seed/yoda/600/400',
      message:'The force is strong with you, let’s discuss it.'
  },{
      id :26,
      name:'Zoe Saldana',
      profileimage:'https://picsum.photos/seed/zoesaldana/600/400',
      message:'I have some exciting news about my latest project!'
  },{
    id: 27,
    name: "Alan Turing",
    profileimage: "https://picsum.photos/seed/alanturing/600/400",
    message: "I have a new algorithm I’d like to share with you.",
  },{
    id: 28,
    name: "Beyoncé Knowles",
    profileimage: "https://picsum.photos/seed/beyonceknowles/600/400",
    message: "Your music is inspiring, let’s collaborate!",
  },{
    id: 29,
    name: "Alice Johnson",
    profileimage: "https://picsum.photos/seed/alicejohnson/600/400",
    message: "I have a new art piece I’d love to show you.",
  },{
    id: 30,
    name: "Charlie Green",
    profileimage: "https://picsum.photos/seed/charliegreen/600/400",
    message: "Let’s plan a trip together soon, it’s been a while!",
  }
]

export { posts, notifications, Friends, marketplace , messages };